# Generated by Django 5.0.1 on 2024-02-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectivesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('elective_name', models.CharField(max_length=100)),
                ('offering_department', models.CharField(max_length=50)),
                ('offering_strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('jntu_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('curr_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultsElectiveWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('elective_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.electivesinfo')),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsDeptWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('elective_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.electivesinfo')),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.studentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='electivesinfo',
            name='not_allowed_students',
            field=models.ManyToManyField(blank=True, to='admin_portal.studentinfo'),
        ),
    ]
