# Generated by Django 5.0.1 on 2024-02-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_electivesinfo_studentinfo_resultselectivewise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTime',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='resultsdeptwise',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultselectivewise',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
