# Generated by Django 5.0.1 on 2024-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_registrationtime_alter_resultsdeptwise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
