# Generated by Django 5.0.2 on 2024-02-16 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_alter_registrationtime_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('e_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('elective_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DummyTable',
        ),
        migrations.AlterField(
            model_name='resultselectivewise',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.department'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.department'),
        ),
        migrations.AlterField(
            model_name='electivesinfo',
            name='elective_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.elective'),
        ),
        migrations.AlterField(
            model_name='resultselectivewise',
            name='elective_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.elective'),
        ),
        migrations.DeleteModel(
            name='ResultsDeptWise',
        ),
    ]
