# Generated by Django 5.0.2 on 2024-02-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_department_elective_delete_dummytable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivesinfo',
            name='offering_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.department'),
        ),
    ]
