# Generated by Django 5.0.2 on 2024-02-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_alter_electivesinfo_offering_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='registrationtime',
            name='time',
        ),
        migrations.AddField(
            model_name='registrationtime',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationtime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationtime',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationtime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
